# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pibpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.CharField(max_length=15)),
                ('fornavn', models.CharField(max_length=250)),
                ('efternavn', models.CharField(max_length=250)),
                ('records', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pibrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=250, null=True)),
                ('age', models.CharField(max_length=250, null=True)),
                ('check1', models.CharField(max_length=250, null=True)),
                ('check2', models.CharField(max_length=250, null=True)),
                ('check21', models.CharField(max_length=250, null=True)),
                ('check22', models.CharField(max_length=250, null=True)),
                ('radio22', models.CharField(max_length=250, null=True)),
                ('check23', models.CharField(max_length=250, null=True)),
                ('check3', models.CharField(max_length=250, null=True)),
                ('check31', models.CharField(max_length=250, null=True)),
                ('check32', models.CharField(max_length=250, null=True)),
                ('check33', models.CharField(max_length=250, null=True)),
                ('check34', models.CharField(max_length=250, null=True)),
                ('check35', models.CharField(max_length=250, null=True)),
                ('check36', models.CharField(max_length=250, null=True)),
                ('check37', models.CharField(max_length=250, null=True)),
                ('check4', models.CharField(max_length=250, null=True)),
                ('check5', models.CharField(max_length=250, null=True)),
                ('cerebral', models.CharField(max_length=250, null=True)),
                ('FDG', models.CharField(max_length=250, null=True)),
                ('project', models.CharField(max_length=250, null=True)),
                ('date', models.CharField(max_length=250, null=True)),
                ('c11', models.CharField(max_length=250, null=True)),
                ('PET', models.CharField(max_length=250, null=True)),
                ('quality', models.CharField(max_length=250, null=True)),
                ('fusioneret', models.CharField(max_length=250, null=True)),
                ('fromdate', models.CharField(max_length=250, null=True)),
                ('sammenholdt', models.CharField(max_length=250, null=True)),
                ('HFrontal', models.CharField(max_length=250, null=True)),
                ('HPariental', models.CharField(max_length=250, null=True)),
                ('HStriatum', models.CharField(max_length=250, null=True)),
                ('HOccipital', models.CharField(max_length=250, null=True)),
                ('VFrontal', models.CharField(max_length=250, null=True)),
                ('VPariental', models.CharField(max_length=250, null=True)),
                ('VStriatum', models.CharField(max_length=250, null=True)),
                ('VOccipital', models.CharField(max_length=250, null=True)),
                ('cerebrum', models.CharField(max_length=250, null=True)),
                ('ingen_amyl', models.CharField(max_length=250, null=True)),
                ('oeget_amyl', models.CharField(max_length=250, null=True)),
                ('konklussion', models.CharField(max_length=250, null=True)),
                ('intern_t', models.CharField(max_length=250, null=True)),
                ('opretter_id', models.CharField(max_length=250, null=True)),
                ('interessant', models.CharField(max_length=250, null=True)),
                ('MR_beskrivelse', models.CharField(max_length=250, null=True)),
                ('StrukturelSkanning', models.CharField(max_length=250, null=True)),
                ('fraStrukturelSkanning', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null=True)),
                ('firstname', models.CharField(max_length=250, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('role', models.CharField(max_length=250, null=True)),
                ('authenticated', models.CharField(max_length=250, null=True)),
                ('pibrecords', models.ManyToManyField(to='riget.Pibrecord')),
            ],
        ),
    ]
