# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0004_auto_20170314_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FET_records',
        ),
        migrations.DeleteModel(
            name='FET_records_deleted',
        ),
    ]
