# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0006_fet_records_fet_records_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FET_persons',
        ),
        migrations.DeleteModel(
            name='FET_persons_deleted',
        ),
        migrations.DeleteModel(
            name='FET_record_images',
        ),
        migrations.DeleteModel(
            name='FET_records',
        ),
        migrations.DeleteModel(
            name='FET_records_deleted',
        ),
        migrations.DeleteModel(
            name='FET_users',
        ),
    ]
