# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0010_fet_records_fet_records_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fetpersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPR', models.CharField(max_length=128)),
                ('firstename', models.CharField(max_length=250)),
                ('FDG', models.BooleanField(default=False)),
                ('avastin', models.BooleanField(default=False)),
                ('lasrChangedBy', models.CharField(default='admin', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fetpersonsdeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPR', models.CharField(max_length=128)),
                ('firstename', models.CharField(max_length=250)),
                ('FDG', models.BooleanField(default=False)),
                ('avastin', models.BooleanField(default=False)),
                ('lasrChangedBy', models.CharField(default='admin', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fetrecordimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgID', models.CharField(max_length=250)),
                ('recordID', models.IntegerField(default=0)),
                ('CPR', models.CharField(max_length=250)),
                ('filename', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fetrecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPR', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('scandato', models.DateField(default=datetime.date.today)),
                ('scanner', models.CharField(max_length=250)),
                ('scantype_type', models.CharField(max_length=250)),
                ('scantype_pct', models.CharField(max_length=250)),
                ('tumor_type', models.CharField(max_length=250)),
                ('tumor_andet', models.CharField(max_length=250)),
                ('kurveform', models.CharField(max_length=250)),
                ('indikation_uafklaret_process', models.BooleanField(default=False)),
                ('indikation_gradering', models.BooleanField(default=False)),
                ('indikation_biopsioptimering', models.BooleanField(default=False)),
                ('indikation_malign_transformation', models.BooleanField(default=False)),
                ('indikation_recidiv_straalefoelger', models.BooleanField(default=False)),
                ('indikation_rt_planlaegning', models.BooleanField(default=False)),
                ('indikation_monitorering', models.BooleanField(default=False)),
                ('indikation_tidlig_postop_vurdering', models.BooleanField(default=False)),
                ('indikation_epi_kir', models.BooleanField(default=False)),
                ('indikation_praeoperativ_planlaegning', models.BooleanField(default=False)),
                ('indikation_pseudo_progression', models.BooleanField(default=False)),
                ('indikation_projekt', models.CharField(max_length=250, null=True)),
                ('indikation_andet', models.CharField(max_length=250, null=True)),
                ('roi_b_avg', models.FloatField(default=0)),
                ('roi_suv_threshold', models.FloatField(default=0)),
                ('roi_suv_mean', models.FloatField(default=0)),
                ('roi_t_mean_b', models.FloatField(default=0)),
                ('roi_suv_max', models.FloatField(default=0)),
                ('roi_t_max_b', models.FloatField(default=0)),
                ('roi_tumor_vol', models.FloatField(default=0)),
                ('mr_t1_kontrastop', models.BooleanField(default=False)),
                ('uni_multi_fokal', models.CharField(max_length=250)),
                ('konklusion_followup', models.CharField(max_length=250)),
                ('kommentar', models.CharField(max_length=250, null=True)),
                ('active', models.CharField(max_length=200)),
                ('kbg_ml', models.IntegerField(default=0)),
                ('interessant_case', models.IntegerField(default=0)),
                ('MR_DCE', models.IntegerField(default=0)),
                ('MR_DSC', models.IntegerField(default=0)),
                ('filter_t', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fetrecordsdeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPR', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('scandato', models.DateField(default=datetime.date.today)),
                ('scanner', models.CharField(max_length=250)),
                ('scantype_type', models.CharField(max_length=250)),
                ('scantype_pct', models.CharField(max_length=250)),
                ('tumor_type', models.CharField(max_length=250)),
                ('tumor_andet', models.CharField(max_length=250)),
                ('kurveform', models.CharField(max_length=250)),
                ('indikation_uafklaret_process', models.BooleanField(default=False)),
                ('indikation_gradering', models.BooleanField(default=False)),
                ('indikation_biopsioptimering', models.BooleanField(default=False)),
                ('indikation_malign_transformation', models.BooleanField(default=False)),
                ('indikation_recidiv_straalefoelger', models.BooleanField(default=False)),
                ('indikation_rt_planlaegning', models.BooleanField(default=False)),
                ('indikation_monitorering', models.BooleanField(default=False)),
                ('indikation_tidlig_postop_vurdering', models.BooleanField(default=False)),
                ('indikation_epi_kir', models.BooleanField(default=False)),
                ('indikation_praeoperativ_planlaegning', models.BooleanField(default=False)),
                ('indikation_pseudo_progression', models.BooleanField(default=False)),
                ('indikation_projekt', models.CharField(max_length=250, null=True)),
                ('indikation_andet', models.CharField(max_length=250, null=True)),
                ('roi_b_avg', models.FloatField(default=0)),
                ('roi_suv_threshold', models.FloatField(default=0)),
                ('roi_suv_mean', models.FloatField(default=0)),
                ('roi_t_mean_b', models.FloatField(default=0)),
                ('roi_suv_max', models.FloatField(default=0)),
                ('roi_t_max_b', models.FloatField(default=0)),
                ('roi_tumor_vol', models.FloatField(default=0)),
                ('mr_t1_kontrastop', models.BooleanField(default=False)),
                ('uni_multi_fokal', models.CharField(max_length=250)),
                ('konklusion_followup', models.CharField(max_length=250)),
                ('kommentar', models.CharField(max_length=250, null=True)),
                ('active', models.CharField(max_length=200)),
                ('kbg_ml', models.IntegerField(default=0)),
                ('interessant_case', models.IntegerField(default=0)),
                ('MR_DCE', models.IntegerField(default=0)),
                ('MR_DSC', models.IntegerField(default=0)),
                ('filter_t', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fetusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('md5pass', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='FET_persons',
        ),
        migrations.DeleteModel(
            name='FET_persons_deleted',
        ),
        migrations.DeleteModel(
            name='FET_record_images',
        ),
        migrations.DeleteModel(
            name='FET_records',
        ),
        migrations.DeleteModel(
            name='FET_records_deleted',
        ),
        migrations.DeleteModel(
            name='FET_users',
        ),
    ]
