# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0011_auto_20170320_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='fet_persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
