# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0012_fet_persons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fet_persons',
            new_name='riget_fet_persons',
        ),
    ]
