# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0013_auto_20170320_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetrecordimages',
            name='imgID',
        ),
        migrations.RemoveField(
            model_name='fetrecordimages',
            name='recordID',
        ),
        migrations.AddField(
            model_name='fetrecordimages',
            name='img',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fetrecordimages',
            name='record',
            field=models.IntegerField(default=0),
        ),
    ]
