# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetpersons',
            old_name='firstename',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='fetpersons',
            name='lastname',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
